### ISSUE TITLE
Sketch 40: Reference Layer creation (cmd: "create font metrics", "create baseline layer") broken

### ISSUE THREAD

**Issue by automat** [automat/sketch-text-tools#3]

**Comment by abhinittiwari-zz** [comment]
This is the exception that running 'Create Font Metrics` throws– 

`Exception: TypeError: style.borders().addNewStylePart is not a function. (In 'style.borders().addNewStylePart()', 'style.borders().addNewStylePart' is undefined)
`

**Comment by detj** [comment]
@abhinittiwari how should I reproduce this? steps would help to debug.

**Comment by abhinittiwari-zz** [comment]
@detj 
- install the plugin with the latest version of sketch. 
- add a text layer, select it and run 'Create Font Metrics'
- See errors in Console.app

**Comment by detj** [comment]
Fixed https://github.com/automat/sketch-text-tools/pull/4

@automat can you review please?

**Comment by automat** [comment]
Fixed: e4eee88dada947f072680b47d4255dba91fe68ff
